# Generated by Django 5.2.6 on 2025-09-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.CharField(db_column='T001biografia', max_length=5000, unique=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='T002IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(db_column='T002Editorial', max_length=200)),
                ('direccion', models.TextField(db_column='T002Direccion', max_length=200)),
                ('telefono', models.TextField(db_column='T002Fechalimite', max_length=200)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
    ]
