# Generated by Django 5.2.6 on 2025-09-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T003IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre_miembro', models.CharField(db_column='T003NombreMiembro', max_length=100)),
                ('apellido_miembro', models.CharField(db_column='T003ApellidoMiembro', max_length=100)),
                ('email_miembro', models.EmailField(db_column='T003EmailMiembro', max_length=40)),
                ('fecha_membresia', models.DateField(db_column='T003FechaMembresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T003Miembro',
            },
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, db_column='T001Biografia', null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='direccion',
            field=models.CharField(db_column='T002Direccion', max_length=200),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(blank=True, db_column='T002Telefono', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T004IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T004Titulo', max_length=200)),
                ('resumen', models.TextField(blank=True, db_column='T004Resumen', null=True)),
                ('isbn', models.CharField(db_column='T004ISBN', max_length=20, unique=True)),
                ('anio_publicacion', models.IntegerField(db_column='T004AnioPublicacion')),
                ('autor', models.ForeignKey(db_column='T001IdAutor', on_delete=django.db.models.deletion.CASCADE, to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='T002IdEditorial', on_delete=django.db.models.deletion.CASCADE, to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T004Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_devolucion', models.DateField(blank=True, db_column='T005FechaDevolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T004IdLibro', on_delete=django.db.models.deletion.CASCADE, to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='T003IdMiembro', on_delete=django.db.models.deletion.CASCADE, to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
