# Generated by Django 5.2.6 on 2025-09-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_miembro_alter_autor_biografia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'editoriales'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'miembros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'prestamos'},
        ),
    ]
